#数据源配置
spring:
  redis:
    ##redis 单机环境配置
    host: 183.131.15.11
    port: 6979
    password: bms_pwd~!@123
    #    host: 127.0.0.1
    #    port: 6379
    #    password:
    database: 10
    #    database: 0
    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.96:3306/rtb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: dba
    password: dba@2020
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 30
      max-lifetime: 180000
      idle-timeout: 60000
      connection-timeout: 20000
      minimum-idle: 5

swagger:
  enable: true
